.docker-integration-build-base:
  stage: integration-build
  script:
    - cd docker/plugins-docker
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --tag $CI_REGISTRY/faradaysec/cloud/faraday_agent_dispatcher:$IMAGE_TAG .
    - docker push $CI_REGISTRY/faradaysec/cloud/faraday_agent_dispatcher:$IMAGE_TAG
  tags:
    - shell
  rules:
    - when: never

docker-integration-build-branch:
  extends: .docker-integration-build-base
  variables:
    IMAGE_TAG: "plugins-testing-$CI_COMMIT_BRANCH"
  rules:
    - !reference [.devel-branch-manual, rules]
    - when: never

docker-integration-build-main:
  extends: .docker-integration-build-base
  variables:
    IMAGE_TAG: "base"
  rules:
    - !reference [.dev-staging-master-manual, rules]
    - !reference [.daily-control, rules]
    - when: never

docker-integration-build-tag:
  extends: .docker-integration-build-base
  variables:
    IMAGE_TAG: "base-tag"
  rules:
    - !reference [.on-release, rules]
    - when: never
