.integration_executor_testing_base:
  stage: integration-test
  script:
    - apt-get update
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .[test]
    - cd tests/plugins-docker
    - pytest . --capture=sys -v --color=yes --disable-warnings

integration_executor_testing_branch:
  extends: .integration_executor_testing_base
  variables:
    IMAGE_TAG: "plugins-testing-$CI_COMMIT_BRANCH"
  image: registry.gitlab.com/faradaysec/cloud/faraday_agent_dispatcher:$IMAGE_TAG
  rules:
    - !reference [.devel-branch-manual, rules]
    - when: never

integration_executor_testing_main:
  extends: .integration_executor_testing_base
  image: registry.gitlab.com/faradaysec/cloud/faraday_agent_dispatcher:base
  rules:
    - !reference [.dev-staging-master-manual, rules]
    - !reference [.daily-control, rules]
    - when: never
