
publish_pypi:
    image: python:3
    stage: publish
    script:
      - apt-get update -qy
      - pip install twine
      - pip install setuptools
      - pip install pkginfo
      - python setup.py sdist bdist_wheel
      - twine upload -u $PYPI_USER -p $PYPI_PASS dist/* --verbose
    rules:
    - !reference [.on-release, rules]
