integration_executor_testing:
  image: registry.gitlab.com/faradaysec/cloud/faraday_agent_dispatcher:dispatcher-testing
  stage: testing
  script:
    - apt-get update
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .[test]
    - pip install pytest_regressions
    - cd tests/regression
    - pytest .
  rules:
    - when: always
