integration_executor_testing:
  image: registry.gitlab.com/faradaysec/cloud/faraday_agent_dispatcher:dispatcher-testing
  stage: regression-test
  script:
    - apt-get update
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .[test]
    - pip install pytest_regressions
    - cd tests/regression
    - pytest . --capture=sys -v --color=yes --disable-warnings
  rules:
    - when: always
  artifacts:
    paths:
      - tests/regression/test_executors/*
    expire_in: 7 days
    when: always
