integration_executor_testing:
  image: registry.gitlab.com/faradaysec/cloud/faraday_agent_dispatcher:dispatcher-testing
  stage: testing
  script:
    - apt-get update
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .[test]
    - export EXECUTOR_CONFIG_PORT_LIST=1-10000
    - export EXECUTOR_CONFIG_TARGET=www.scanme.org
    - python3 faraday_agent_dispatcher/static/executors/official/nmap.py
  rules:
    - when: always
