
integration_faraday:
    stage: post_testing
    variables:
        DISPATCHER_REF: $CI_COMMIT_REF_NAME
    trigger:
        project: faradaysec/devops
        strategy: depend
    rules:
        - if: '$CI_COMMIT_REF_NAME =~ /^(dev|master)$/'
          when: on_success
        - if: $INTEGRATION
          when: on_success
