site_name: Faraday Agent Dispatcher
site_description: Faraday Agent Dispatcher launches any security tools and send results to FaradaySEC
site_author: Faradaysec
site_url: https://faradaysec.com
repo_name: infobyte/faraday_agent_dispatcher
repo_url: https://github.com/infobyte/faraday_agent_dispatcher
theme:
    name: material
    logo: images/logo.svg
    icon:
        repo: fontawesome/brands/github-alt
    favicon: images/favicon.png
    language: en
    features:
        - navigation.tabs
nav:
    - Home: index.md
    - Getting started: getting-started.md
    - Technical:
          - Architecture: technical/arch.md
          - Agents: technical/agents.md
    - Misc:
          - Docker: misc/docker.md
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: True
    - codehilite:
        linenums: true
        noclasses: True
    - toc:
        permalink: true
    - pymdownx.magiclink:
        repo_url_shortener: True
        repo_url_shorthand: True
        social_url_shorthand: True
        # more options on magiclink https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#options
        provider: 'github'
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/infobyte/faraday_agent_dispatcher
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/faradaysec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/faradaysec/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/faradaysec
extra_javascript:
    - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
extra_css:
    - css/faraday_doc.css
    - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
