SAST-bandit:
  stage: .pre
  image: python:3
  tags: 
    - faradaytests
  script:
    - pip3 install bandit
    - mkdir /results
    - "bandit -r ${CI_PROJECT_DIR}/faraday_agent_dispatcher -o /results/output.xml -f xml -s B314,B404,B405,B501,B603"
  after_script:
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt update
    - apt-get install software-properties-common -y
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    - apt update
    - apt install vault -y
    - setcap cap_ipc_lock= /usr/bin/vault
    - !reference [ .get_secrets, script ]
    - pip3 install faraday-cli
    - if [[ $(grep -c testcase /results/output.xml) -gt 0 ]]; then (faraday-cli auth -f $FARADAY_URL -u $FARADAY_USER -p $FARADAY_PASSWORD && faraday-cli tool report /results/output.xml -w $DEVSECOPS_WORKSPACE --vuln-tag $CI_PROJECT_NAME); else (echo 'no vulns dettected' && exit 0); fi
  rules:
    - when: on_success

flake8:
    image: python:3
    stage: .pre
    script:
      - pip install flake8
      - flake8 --max-line-length=119 .

black:
    image: python:3
    stage: .pre
    script:
      - pip install black
      - black --line-length=119 --check .
