.parse-secrets: &parse-secrets
- FARADAY_URL=$(cat $FARADAY_URL)
- FARADAY_USER=$(cat $FARADAY_USER)
- FARADAY_PASSWORD=$(cat $FARADAY_PASSWORD)
- DEVSECOPS_WORKSPACE=$(cat $DEVSECOPS_WORKSPACE)

SAST-bandit:
  stage: .pre
  image: python:3.11
  tags:
    - faradaytests
  allow_failure: true
  script:
    - pip3 install --no-cache-dir bandit
    - mkdir /results
    - "bandit -r ${CI_PROJECT_DIR}/faraday_agent_dispatcher -o /results/output.xml -f xml -s B314,B404,B405,B501,B603"
  extends: .get-secrets
  after_script:
    - *parse-secrets
    - |
        if ! grep -q testcase /results/output.xml 2>/dev/null; then
          echo 'no vulns detected'
          exit 0
        fi
        python3 -m pip install --no-cache-dir setuptools faraday-cli
        faraday-cli auth -f "$FARADAY_URL" -u "$FARADAY_USER" -p "$FARADAY_PASSWORD"
        faraday-cli tool report /results/output.xml -w "$DEVSECOPS_WORKSPACE" --vuln-tag "$CI_PROJECT_NAME"
  rules:
    - when: on_success

flake8:
    image: python:3
    stage: .pre
    script:
      - pip install flake8
      - flake8 --max-line-length=119 .

black:
    image: python:3
    stage: .pre
    script:
      - pip install black
      - black --line-length=119 --check .
